"""Form-owned agent identity and certificate lifecycle contracts.

These models describe Form's durable identity registry.  They are deliberately
separate from telemetry payloads: an agent cannot select its own identity by
putting an ``agent_id`` in an upload.  Form derives the principal from the
verified TLS peer certificate and this registry instead.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from analyzer.schemas.common import StrictModel, Timestamp
from pydantic import Field, field_validator, model_validator


class AgentScope(StrEnum):
    """Telemetry families an agent identity may submit."""

    ASSET_REPORT = "asset-report"
    TRACE_BATCH = "trace-batch"
    GUARD_EVENT = "guard-event"


class AgentIdentityState(StrEnum):
    """Durable state of an agent identity."""

    ACTIVE = "active"
    REVOKED = "revoked"


class AgentCertificateState(StrEnum):
    """Lifecycle state of one immutable certificate generation."""

    STAGED = "staged"
    ACTIVE = "active"
    RETIRED = "retired"
    REVOKED = "revoked"


class AgentCertificate(StrictModel):
    """Non-secret metadata retained for one issued client certificate."""

    agent_id: str = Field(min_length=1, max_length=128)
    generation: int = Field(ge=1)
    serial_number: str = Field(min_length=1, max_length=64, pattern=r"^[0-9a-f]+$")
    cert_sha256: str = Field(min_length=64, max_length=64, pattern=r"^[0-9a-f]{64}$")
    spki_sha256: str = Field(min_length=64, max_length=64, pattern=r"^[0-9a-f]{64}$")
    state: AgentCertificateState
    not_before: Timestamp
    not_after: Timestamp
    created_at: Timestamp
    activated_at: Timestamp | None = None
    retired_at: Timestamp | None = None
    overlap_until: Timestamp | None = Field(
        default=None,
        description="Retired certificate remains valid through this rotation overlap instant",
    )
    revoked_at: Timestamp | None = None

    @field_validator("serial_number", "cert_sha256", "spki_sha256", mode="before")
    @classmethod
    def _normalize_hex(cls, value: Any) -> Any:
        if isinstance(value, str):
            value = value.strip().lower()
            if value.startswith("0x"):
                value = value[2:]
        return value

    @model_validator(mode="after")
    def _valid_window(self) -> AgentCertificate:
        if self.not_after <= self.not_before:
            raise ValueError("certificate not_after must be later than not_before")
        return self


class AgentIdentity(StrictModel):
    """Stable server-owned binding between a target, host, scopes, and agent id."""

    agent_id: str = Field(min_length=1, max_length=128, pattern=r"^[A-Za-z0-9._~-]+$")
    target_id: str = Field(min_length=1, max_length=256)
    canonical_host_id: str = Field(min_length=1, max_length=256)
    scopes: list[AgentScope] = Field(min_length=1)
    state: AgentIdentityState = AgentIdentityState.ACTIVE
    generation: int = Field(default=0, ge=0)
    created_at: Timestamp
    updated_at: Timestamp
    revoked_at: Timestamp | None = None
    certificates: list[AgentCertificate] = Field(default_factory=list)

    @field_validator("scopes", mode="before")
    @classmethod
    def _canonical_scopes(cls, value: Any) -> Any:
        if isinstance(value, (list, tuple, set, frozenset)):
            normalized = {
                item.value if isinstance(item, AgentScope) else str(item).strip() for item in value
            }
            return sorted(scope for scope in normalized if scope)
        return value

    @model_validator(mode="after")
    def _consistent_generations(self) -> AgentIdentity:
        if any(certificate.agent_id != self.agent_id for certificate in self.certificates):
            raise ValueError("certificate belongs to a different agent identity")
        highest = max((certificate.generation for certificate in self.certificates), default=0)
        if highest > self.generation:
            raise ValueError("certificate generation exceeds identity generation")
        return self


class VerifiedAgentIdentity(StrictModel):
    """Principal resolved exclusively from a verified TLS certificate."""

    agent_id: str
    target_id: str
    canonical_host_id: str
    scopes: list[AgentScope]
    certificate: AgentCertificate


class AgentCertificateBundle(StrictModel):
    """One-time deployment material returned after staging a generation.

    The leaf private key is generated by Form and exists only in this return
    value.  Neither the identity repository nor the CA service persists it.
    ``repr=False`` prevents accidental log disclosure while preserving explicit
    serialization for the SFTP deployment boundary.
    """

    identity: AgentIdentity
    certificate: AgentCertificate
    certificate_pem: str
    private_key_pem: str = Field(repr=False)
    ca_certificate_pem: str


__all__ = [
    "AgentCertificate",
    "AgentCertificateBundle",
    "AgentCertificateState",
    "AgentIdentity",
    "AgentIdentityState",
    "AgentScope",
    "VerifiedAgentIdentity",
]
