name: DCO

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: read
  statuses: write

jobs:
  dco:
    name: Signed-off-by
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: dcoapp/app@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
